"""Initial schema creation

Revision ID: 1c12f3468b9d
Revises: 74a21c4b4cc5
Create Date: 2026-08-03 18:31:57.452120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c12f3468b9d'
down_revision: Union[str, Sequence[str], None] = '74a21c4b4cc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('password', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'employee', ['password'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee', type_='unique')
    op.drop_column('employee', 'password')
    # ### end Alembic commands ###
