"""Rename columns in leave_quote table

Revision ID: 44409cec5ad0
Revises: 602d26421915
Create Date: 2026-08-21 20:48:05.630433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44409cec5ad0'
down_revision: Union[str, Sequence[str], None] = '602d26421915'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave_quote',
    sa.Column('quote_id', sa.UUID(), nullable=False),
    sa.Column('emp_id', sa.UUID(), nullable=True),
    sa.Column('sick_leave_allotted', sa.Integer(), nullable=False),
    sa.Column('sick_leave_remaining', sa.Integer(), nullable=False),
    sa.Column('casual_leave_allotted', sa.Integer(), nullable=False),
    sa.Column('casual_leave_remaining', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['emp_id'], ['employee.emp_id'], ),
    sa.PrimaryKeyConstraint('quote_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leave_quote')
    # ### end Alembic commands ###
