"""Rename columns in leave_quote table

Revision ID: 602d26421915
Revises: 1c12f3468b9d
Create Date: 2026-08-21 20:39:22.082814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '602d26421915'
down_revision: Union[str, Sequence[str], None] = '1c12f3468b9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('employee_password_key'), 'employee', type_='unique')
    op.add_column('leave_quote', sa.Column('sick_leave_allotted', sa.Integer(), nullable=False))
    op.add_column('leave_quote', sa.Column('sick_leave_remaining', sa.Integer(), nullable=False))
    op.add_column('leave_quote', sa.Column('casual_leave_allotted', sa.Integer(), nullable=False))
    op.drop_column('leave_quote', 'sick_leave_allocated')
    op.drop_column('leave_quote', 'casual_leave_allocated')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave_quote', sa.Column('casual_leave_allocated', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('leave_quote', sa.Column('sick_leave_allocated', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('leave_quote', 'casual_leave_allotted')
    op.drop_column('leave_quote', 'sick_leave_remaining')
    op.drop_column('leave_quote', 'sick_leave_allotted')
    op.create_unique_constraint(op.f('employee_password_key'), 'employee', ['password'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
